@startuml Component Diagram

package "Energy Management System" {
    package "System Variables" {
        [CPVPanel] 
        [CHouse] 
    }
        package "System Responders" {
        [CEnergyContext] ..> [CStorageSystem] : "requires"
        [CEnergyContext] ..> [CGrid] : "requires"
    }

    package "Notifications" {
        [IObservable]
        [IObserver]
    } 

    package "Storage Components" {
        [IController]
        [IInverter]
        [IBattery]
    }

    package "Vendors" {
        [CVendorABattery]
        [CVendorBInverter]
        [CVendorXController]
    }

    package "Adapters" {
        [CVendorABatteryAdapter]
        [CVendorBInverterAdapter]
        [CVendorXControllerAdapter]
    }

    package "Strategy" {
        [CSupplyFromPVStrategy]
        [CSupplyFromStorageStrategy]
    }

    [CEnergyContext] o-- [CStorageSystem] : shares
    [CEnergyContext] o-- [CGrid] : shares

    [CPVPanel] --|> [IObservable] : "implements"
    [CHouse] --|> [IObservable] : "implements"

    [CPVPanel] ..> [IObserver] : "weak ref"
    [CHouse] ..> [IObserver] : "weak ref"

    [IObservable] --> [IObserver] : "notifies"

    [CEnergyContext] --|> [IEnergyContext] : "implements"
    [IEnergyContext] --|> [IObservable] : "inherits"
    [CEnergyContext] --|> [IObserver] : "implements"
    [CEnergyContext] ..> [IObserver] : "weak ref"

    [CStorageSystem] *-- [IController] : "owns"
    [CStorageSystem] *-- [IInverter] : "owns"
    [CStorageSystem] *-- [IBattery] : "owns"
    [CStorageSystem] *-- [CStorageFactory] : "contains"

    [CStorageFactory] *-- [CReadConfig] : "contains"

    [CReadConfig] ..> "nlohmann::json" : depends 

    [CVendorABatteryAdapter] *-- [CVendorABattery] : "contains"
    [CVendorABatteryAdapter] --|> [IBattery] : "implements"

    [CVendorBInverterAdapter] *-- [CVendorBInverter] : "contains"
    [CVendorBInverterAdapter] --|> [IInverter] : "implements"

    [CVendorXControllerAdapter] *-- [CVendorXController] : "contains"
    [CVendorXControllerAdapter] --|> [IController] : "implements"
    [CVendorXControllerAdapter] ..> [IEnergyContext] : "depends"

    [CSupplyFromPVStrategy] --|> [IEnergyStrategy] : "implements"
    [CSupplyFromStorageStrategy] --|> [IEnergyStrategy] : "implements"

    [CVendorXController] *-- [IEnergyStrategy] : "owns"

}

@enduml
