@startuml Sequence Diagram
title Energy Management System

actor Main

participant "CPVPanel" as CPV
participant "CHouse" as House
participant "CStorageSystem" as Storage
participant "CEnergyContext" as EnergyContext
participant "Controller\n(CVendorXControllerAdapter)" as Controller
participant "SupplyFromPVStrategy" as PVStrategy
participant "SupplyFromStorageStrategy" as StorageStrategy

Main -> CPV: updateMeasurements(power, volt, current)
CPV -> CPV: Check if "power" > threshold
CPV -> EnergyContext: notifyObservers("power", power)

Main -> House: updateMeasurements(power, volt, current, freq)
House -> House: Check if "power" > threshold
House -> EnergyContext: notifyObservers("power", power)

EnergyContext -> EnergyContext: onUpdate(source, "power", value)
EnergyContext -> Controller: notifyObservers("power", value)

Main -> EnergyContext: setBatteryTemperature(temp)
BatteryManager -> Storage: getMaxBatteryTemp()
activate Storage
Storage --> BatteryManager: maxTemp
deactivate Storage
alt (temp > threshold && m_Values["temp"] < threshold) || (temp < threshold && m_Values["temp"] > threshold)
    EnergyContext -> Controller: notifyObservers("temp", value)
    EnergyContext -> EnergyContext: update m_Values["temp"] = temp
end

Controller -> Controller: onUpdate(source, "power", value)
Controller -> EnergyContext: getPVPower()
activate EnergyContext
EnergyContext --> Controller: pvPower
deactivate EnergyContext
Controller -> EnergyContext: getHouseConsumption()
activate EnergyContext
EnergyContext --> Controller: houseConsumption
deactivate EnergyContext
Controller -> Controller: determineStrategy(context)
alt PV Power > House Consumption
    Controller -> PVStrategy: executeStrategy(context)
    PVStrategy -> PVStrategy: manageEnergy(context)
else
    Controller -> StorageStrategy: executeStrategy(context)
    StorageStrategy -> StorageStrategy: manageEnergy(context)
end

Controller -> Controller: onUpdate(source, "temp", value)
alt (m_CoolerIsOn == true)
    Controller-> Controller: deactivateCooler()
else
    Controller-> Controller: activateCooler()
end

@enduml
